mode     : selfcontained
framework: purus
github:
  user: arthur-flam
  repo: blog

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



