mode     : selfcontained
framework: purus
github:
  user: arthur-flam
  repo: FormationR

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../libraries
  assets: ../assets

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: arthur-flam



